/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.print.PrinterException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Nusky Shafik
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form PrintInventory
     */
    public Print() {
        initComponents();
    }
    
    String subTotal, pay, balance, discount, fname, lname, billNo;
    
    
    

    Print(String billNo, String fname, String subTotal, String pay, String balance, String discount, TableModel tablemodel) {
        initComponents();
        this.fname = fname;
        this.subTotal = subTotal;
        this.pay = pay;
        this.balance = balance;
        this.discount = discount;
        this.billNo = billNo;
        
//        Float dis = Float.parseFloat(discount);
//        
//        Float disAmount = Float.parseFloat(subTotal) * (dis / 100);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        
        txtPrint.setText(txtPrint.getText() + "**************************************\n");
        txtPrint.setText(txtPrint.getText() + "************CITY GROCERIES************\n");
        txtPrint.setText(txtPrint.getText() + "                       \n");
        txtPrint.setText(txtPrint.getText() + "*****************SALE*****************\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "                   " + date);
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "Bill No : " + billNo);
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "Cashier name : " + fname);
        txtPrint.setText(txtPrint.getText() + "\n\n");
        txtPrint.setText(txtPrint.getText() + "--------------------------------------\n");
        txtPrint.setText(txtPrint.getText() + "   Product   \tPrice\tQty\tTotal\n");
        txtPrint.setText(txtPrint.getText() + "--------------------------------------\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        
        for (int i = 0; i < tablemodel.getRowCount(); i++) {
            
            String product = (String) tablemodel.getValueAt(i, 1);
//            String description = (String) tablemodel.getValueAt(i, 2);
            String price = (String) tablemodel.getValueAt(i, 3);
            String qty = (String) tablemodel.getValueAt(i, 4);
            int total = (int) tablemodel.getValueAt(i, 5);
            
            txtPrint.setText(txtPrint.getText()+ "  " + product + " \t" + price + "\t" + qty + "\t" + total);
            txtPrint.setText(txtPrint.getText() + "\n");
            
        }
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        
        txtPrint.setText(txtPrint.getText() + "--------------------------------------\n");
        
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "TOTAL DISCOUNT : " + discount + "%" +"\n");
        txtPrint.setText(txtPrint.getText() + "SUBTOTAL       : " + subTotal +"\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        
        txtPrint.setText(txtPrint.getText() + "--------------------------------------\n");
        
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "CASH   : " + pay +"\n"); 
        txtPrint.setText(txtPrint.getText() + "CHANGE : " + balance +"\n");
        
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "**************************************\n");
        txtPrint.setText(txtPrint.getText() + "*********Thank You Come Again*********\n");
        
        try {
            txtPrint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPrint.setColumns(20);
        txtPrint.setRows(5);
        jScrollPane1.setViewportView(txtPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPrint;
    // End of variables declaration//GEN-END:variables
}
