/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/*import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;*/

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import dbconnection.DBconnect;


/**
 *
 * @author Maneesha
 */
public class SalaryForm extends javax.swing.JFrame {
    
    DBconnect con = new DBconnect();
    PreparedStatement  pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    DefaultTableModel model = null;
    Connection conn = null;
    

    /**
     * Creates new form SalaryForm
     */
    public SalaryForm() {
        initComponents();
       
     conn = DBconnect.connect();
       
     Object col[]={"empId","month","year","bonus","overtime","netSalary"};
    }
    public void tablelod(){
        
        try {
            String sql="Select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.overTime from attendance a,employee e";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        overtimebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        basicsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bonusbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        epfbox = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewslip = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        firstnamebox = new javax.swing.JTextField();
        monthbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastnamebox = new javax.swing.JTextField();
        idbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        netsalarybox = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ratebox = new javax.swing.JTextField();
        etfbox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        totalovertimebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        calnew = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setPreferredSize(new java.awt.Dimension(1367, 657));

        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Basic Salary");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Over Time Hours");

        overtimebox.setEditable(false);
        overtimebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeboxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bonus");

        basicsalary.setEditable(false);
        basicsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryActionPerformed(evt);
            }
        });
        basicsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                basicsalaryKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("EPF");

        bonusbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bonusboxKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ETF");

        epfbox.setEditable(false);
        epfbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfboxActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        viewslip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewslip.setText("VIEW SLIP");
        viewslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewslipActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("First Name");

        firstnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameboxActionPerformed(evt);
            }
        });
        firstnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnameboxKeyPressed(evt);
            }
        });

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "Auguest", "September", "October", "November", "December", " " }));
        monthbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthboxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Month");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Last Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        lastnamebox.setEditable(false);

        idbox.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Year");

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("Net Salary");

        netsalarybox.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "ID", "BasicSalary", "EPF", "ETF", "OverTime"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Rate Per Hour ");

        ratebox.setEditable(false);
        ratebox.setText("250.00");
        ratebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateboxActionPerformed(evt);
            }
        });

        etfbox.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Total Over Time");

        totalovertimebox.setEditable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("VIEW REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        calnew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calnew.setText("CAL");
        calnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calnewActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 102));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("SALARY MANAGEMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(nameLayout.createSequentialGroup()
                                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(51, 51, 51)))
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalovertimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bonusbox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(epfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(etfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(overtimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ratebox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(firstnamebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lastnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nameLayout.createSequentialGroup()
                                            .addComponent(idbox)
                                            .addGap(2, 2, 2)))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewslip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(948, 948, 948)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calnew)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(netsalarybox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameLayout.createSequentialGroup()
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(firstnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(nameLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)
                                                .addGap(5, 5, 5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(nameLayout.createSequentialGroup()
                                                .addComponent(bonusbox)
                                                .addGap(2, 2, 2))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameLayout.createSequentialGroup()
                                        .addComponent(addbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deletebtn)
                                        .addGap(10, 10, 10))))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(overtimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ratebox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calnew)))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(updatebtn)
                                .addGap(18, 18, 18)
                                .addComponent(viewslip)
                                .addGap(20, 20, 20)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalovertimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(netsalarybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void basicsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryActionPerformed
       
    }//GEN-LAST:event_basicsalaryActionPerformed

    private void viewslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewslipActionPerformed
   
        //view slip button
        
       
        
       PaySlip p= new PaySlip();
       PaySlip.jTextField1.setText(SalaryForm.jComboBox2.getSelectedItem().toString());
       PaySlip.jTextField2.setText(SalaryForm.monthbox.getSelectedItem().toString());
       PaySlip.jTextField3.setText(SalaryForm.idbox.getText());
       PaySlip.jTextField5.setText(SalaryForm.firstnamebox.getText());
       PaySlip.jTextField4.setText(SalaryForm.lastnamebox.getText());
       PaySlip.jTextField6.setText(SalaryForm.basicsalary.getText());
       PaySlip.jTextField11.setText(SalaryForm.totalovertimebox.getText());
       PaySlip.jTextField7.setText(SalaryForm.bonusbox.getText());
       PaySlip.jTextField8.setText(SalaryForm.epfbox.getText());
       PaySlip.jTextField9.setText(SalaryForm.etfbox.getText());
       PaySlip.jTextField10.setText(SalaryForm.netsalarybox.getText());
       p.setVisible(true);
       this.dispose();
       
     
    }//GEN-LAST:event_viewslipActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
   
        //search buttton
        
        
    /*
   String name = firstnamebox.getText();
   String month = (String) monthbox.getSelectedItem();
   String s = "select empId from employee where fName like '"+name+"'";
   
   String searchQuery = "select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.overTime from employee e,"
           + " attendance a where fName LIKE '%"+name+"%'";
    PreparedStatement ps;
    ResultSet rs;
    String id=null;
        
        try{
            
            ps = (PreparedStatement) con.connect().prepareStatement(s);
            rs = ps.executeQuery(s);
            if(rs.next()){
                jLabel7.setText(rs.getString("empId"));
                id = jLabel7.getText();
                
            }
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch (SQLException e){
            Logger.getLogger(SalaryForm.class.getName()).log(Level.SEVERE,null,e);
            
        }
        
    String ss = "select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.total_overtimeHours from attendance_report a,employee e where e.empId = a.empID AND a.empID = '"+id+"' and a.month = '"+month+"'";
   
    PreparedStatement ps1;
    ResultSet rs1;    
        
        try{
            
            ps1 = (PreparedStatement) con.connect().prepareStatement(ss);
            rs1 = ps1.executeQuery(ss);
            if(rs1.next()){
                jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            }
            
            
            
        }catch (SQLException e){
            Logger.getLogger(SalaryForm.class.getName()).log(Level.SEVERE,null,e);
               
        }*/
    
         String name = firstnamebox.getText();
         String searchQuery = "select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.overTime from employee e,"
           + " attendance a where fName LIKE '%"+name+"%'";
          PreparedStatement ps;
          ResultSet rs;
        
        
        try{
            
            ps = (PreparedStatement) con.connect().prepareStatement(searchQuery);
            rs = ps.executeQuery(searchQuery);
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch (SQLException e){
            Logger.getLogger(SalaryForm.class.getName()).log(Level.SEVERE,null,e);
            
        }
        
    
    
    
    }//GEN-LAST:event_searchActionPerformed

    private void firstnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameboxActionPerformed
   
    }//GEN-LAST:event_firstnameboxActionPerformed

    private void monthboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthboxActionPerformed
       
    }//GEN-LAST:event_monthboxActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       
        //add button
        
        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();
        String bonus = bonusbox.getText();
        String overTime = totalovertimebox.getText();
        String netSalary = netsalarybox.getText();
        
         PreparedStatement ps;
     
        try{
        String sql = "INSERT INTO salary (empId, month, year, bonus, overtime, netSalary) "+ "VALUES (?,?,?,?,?,?)";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql);
        preparedStatement.setInt(1, Integer.parseInt(empId));
        preparedStatement.setString(2, month);
        preparedStatement.setString(3, year); 
        preparedStatement.setDouble(4, Double.parseDouble(bonus));
        preparedStatement.setDouble(5, Double.parseDouble(overTime));
        preparedStatement.setDouble(6, Double.parseDouble(netSalary));
        preparedStatement.executeUpdate(); 
        
        } catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"inserted successfully");  
      
    
     
    try{
         String sql= "insert into salary (empId,month,year,overtime,netSalary)";
         
     } catch(Exception e){}
         
     
     
        
       
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       
//update button

        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();
        String bonus = bonusbox.getText();
        String overTime = totalovertimebox.getText();
        String netSalary = netsalarybox.getText();
        
         PreparedStatement ps;
     
        try{
        String sql = "UPDATE salary set bonus = ?, overtime= ?, netSalary= ? WHERE empId = ? AND  month =? AND year=?";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql); 
        preparedStatement.setDouble(1, Double.parseDouble(bonus));
        preparedStatement.setDouble(2, Double.parseDouble(overTime));
        preparedStatement.setDouble(3, Double.parseDouble(netSalary));
        preparedStatement.setInt(4, Integer.parseInt(empId));
        preparedStatement.setString(5, month);
        preparedStatement.setString(6, year);
        preparedStatement.executeUpdate(); 
        
        } catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"Update successfully");  
      
    
     
    try{

         
     } catch(Exception e){}
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
      
        //delete button
        
        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();

        
         PreparedStatement ps;
     
        try{
        String sql = "DELETE FROM salary WHERE empId = ? AND  month =? AND year=?";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql); 
        preparedStatement.setInt(1, Integer.parseInt(empId));
        preparedStatement.setString(2, month);
        preparedStatement.setString(3, year);
        preparedStatement.executeUpdate(); 
        
        
        tablelod();
        }
        
        catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"Deleted successfully");  
      
    
     
    try{

         
     } catch(Exception e){}
    
    }//GEN-LAST:event_deletebtnActionPerformed

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        //load details to the table
        
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int selectedRowIndex = jTable1.getSelectedRow();
       
     
        firstnamebox.setText(model.getValueAt(selectedRowIndex,0).toString());
        idbox.setText(model.getValueAt(selectedRowIndex,2).toString());
        lastnamebox.setText(model.getValueAt(selectedRowIndex,1).toString());
        basicsalary.setText(model.getValueAt(selectedRowIndex,3).toString());
        epfbox.setText(model.getValueAt(selectedRowIndex,4).toString());
        etfbox.setText(model.getValueAt(selectedRowIndex,5).toString());
        overtimebox.setText(model.getValueAt(selectedRowIndex,6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void epfboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfboxActionPerformed
        
    }//GEN-LAST:event_epfboxActionPerformed

    private void overtimeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeboxActionPerformed
     
    }//GEN-LAST:event_overtimeboxActionPerformed

    private void rateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateboxActionPerformed
        
    }//GEN-LAST:event_rateboxActionPerformed

    private void basicsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basicsalaryKeyPressed
        
    }//GEN-LAST:event_basicsalaryKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        //calculate net salary
        
        double basicSalary;
        double EPF;
        double ETF;
        double bonus;
        double totalOverTime;
        double netSalary;
        
      basicSalary  = Double.parseDouble(basicsalary.getText());
      EPF  = Double.parseDouble(epfbox.getText());
      ETF  = Double.parseDouble(etfbox.getText());
      bonus = Double.parseDouble(bonusbox.getText());
      totalOverTime  = Double.parseDouble(totalovertimebox.getText());
      
      netSalary =( basicSalary + bonus + totalOverTime) -(EPF + ETF);
      netsalarybox.setText(Double.toString(netSalary));
      
      
     
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameboxKeyPressed
        
        //validate firstname
        
        
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            firstnamebox.setEditable(true);
             }
        else{
            firstnamebox.setEditable(false);
            
        }
    }//GEN-LAST:event_firstnameboxKeyPressed

    private void bonusboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusboxKeyPressed
        
        //validate bonus
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            bonusbox.setEditable(false);
             }
        else{
            bonusbox.setEditable(true);
        }
        
    }//GEN-LAST:event_bonusboxKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

      //clear button
      
         firstnamebox.setText(null);
         lastnamebox.setText(null);
         idbox.setText(null);
         basicsalary.setText(null);
         bonusbox.setText(null);
         epfbox.setText(null);
         etfbox.setText(null);
         overtimebox.setText(null);
         totalovertimebox.setText(null);
         netsalarybox.setText(null);
         
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void calnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calnewActionPerformed
      
        //calculate total over time
         final double Rate = 250.00;
        double overTime;
        double totalOverTime;
        
        overTime = Double.parseDouble(overtimebox.getText());
        
        totalOverTime = overTime * Rate;
        totalovertimebox.setText(Double.toString(totalOverTime));
        
    }//GEN-LAST:event_calnewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        //view report button
        
          MonthlyReport v = new MonthlyReport();
          v.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

      
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryForm().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    public static javax.swing.JTextField basicsalary;
    public static javax.swing.JTextField bonusbox;
    private javax.swing.JButton calnew;
    private javax.swing.JButton deletebtn;
    public static javax.swing.JTextField epfbox;
    public static javax.swing.JTextField etfbox;
    public static javax.swing.JTextField firstnamebox;
    public static javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    public static javax.swing.JTextField lastnamebox;
    public static javax.swing.JComboBox<String> monthbox;
    private javax.swing.JPanel name;
    public static java.awt.TextField netsalarybox;
    private javax.swing.JTextField overtimebox;
    private javax.swing.JTextField ratebox;
    private javax.swing.JButton search;
    public static javax.swing.JTextField totalovertimebox;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewslip;
    // End of variables declaration//GEN-END:variables
}
